version: "3.3"

services:
  giropops:
    image: dilopes/linuxtips-giropops-senhas:1.0
    ports: 
      - 5000:5000
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis

  redis:
    image: redis:alpine3.19
    container_name: redis

networks:
  nw_giropops:
